language: shell
services:
- docker
sudo: required
branches:
  only:
  - master
before_install:
#- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
#  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod +x *.sh
install:
#- chmod 600 ~/.ssh/id_rsa
#- eval $(ssh-agent)
#- ssh-add ~/.ssh/id_rsa
#- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "blademainer"
- git config --global user.email "blademainer@gmail.com"
- sed -i "s/{{GH_TOKEN}}/${GH_TOKEN}/g" push.sh
- "./mkdocs-build.sh"
- sudo chown -R travis public
- "./push.sh"
env:
  global:
  - secure: 2vNnv0mLWC8DhAqiVeDjo7liuIhMjTBqyz7Z7f0GMlZC/MO9ual81J9GVCDNs4+ejRWTD1PPXPELO1n/2Qzg81CWkmEJWLgEGjSKzuYLrWUc7mqm+cYgS3vw+3Vis6tk5W30qbR+n9apuAXX2znRgMAtPAT54Aqssn5H+ecsH7TbWdriWWxbLUJMAsy9mr9Bkze9r1BQCfRhsHlcQV2IK0qW/SjZGlj+ErfwVWHASL9xpq5ySQOUOt/zVUOPpAIjSo4BTZWD9fLqqghX7pckYt7xdQCnmdsTxdbdUljcNOkQjqKDUBy1vvUYMyKyTCjTCgYa1Emw3GOxnEd2bEOELKS+48fLx6Qn79QrYR5NnjLbfu8mHs78u88WL1gfmRTlvEWwAt3NO+CqMtjEIwMszU2QUVd9v8xR0aBu6BVF1i3D3HeKUJGRTeVA5U0UFi/An+ZZe1hlQI/UKcP+6O6jVyweK8meKo8dzmdxD3cm5MuQcil2S+rtQ5TPHOqL00ENYeodFLmgcOIW6EulTjovNDLGA81W01LWkAQiDP1YJ/Du1v0Q4EHaalYNBGbKHPBOuyNw8TqecUXn31gqVSKae8sMDM8dyyhXVJmS+Dzpj/kePR02lrHGX/XNJ6V2+s0+XgrPz5EvZmXzD34XQ7fQyRy2elMtCXX5OpwIFqivmko=
