site_name: PJOC
site_url: http://pjoc.pub
site_description: Distributed pay system.
site_author: Blademainer

repo_url: https://github.com/pjoc-team/pjoc-team.github.io

copyright: Copyright &copy; 2018 <a href="http://pjoc.pub">pjoc.pub</a>.

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
    - yaml
    - rust
#theme:
#    name: cinder
#    include_sidebar: false
#    logo: img/favicon.ico
#    font: false

nav:
    - Home: index.md
    - 1 规范:
      - "1.1 开发规范": specification/dev-specification.md
    - 2 支付:
      - "2.1 设计":
        - "2.1.1 需求设计": pay/design/biz.md
        - "2.1.2 架构": pay/design/architecture.md
        - "2.1.3 管理后台": pay/design/pay-admin.md
    - About: about.md

plugins:
    - search
extra_css:
    - css/extra.css
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
    - js/umlconvert.js
    - js/lunr-chinese.min.js
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - toc
    - smarty
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences: [
              {name: flow, class: uml-flowchart}
             ,{name: sequence, class: uml-sequence-diagram}
             ,{name: mermaid, class: uml-mermaid}
        ]
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: false
    - pymdownx.tilde
    - sane_lists
    - plantuml-markdown
    - pymdownx.arithmatex
#    - plantuml-markdown
#    - pymdown.plantuml
#    - plantuml: 
#        outpath: "images"


