name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: shell
        run: "sh prepare.sh"
      - name: Build
        uses: addnab/docker-run-action@v1
        with:
          image: pjoc/mkdocs:latest
          run: |
            cd ${GITHUB_WORKSPACE}
            pwd
            mkdocs build -d public
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
